# Doc referece https://makefiletutorial.com/#why-do-makefiles-exist

day7: cards.cpp
	g++ -fdiagnostics-color=always -g3 -Wall -std=c++0x cards.cpp -o day7

run: day7
	./day7 $(ARGS)

clean:
	rm -f ./day7
