# Doc referece https://makefiletutorial.com/#why-do-makefiles-exist

day9: oasisreport.cpp
	g++ -fdiagnostics-color=always -g3 -Wall -std=c++17 oasisreport.cpp -o day9

run: day9
	./day9 $(ARGS)

clean:
	rm -f ./oasisreport
	rm -f ./day9
