# Doc referece https://makefiletutorial.com/#why-do-makefiles-exist

day11: galaxy.cpp
	g++ -fdiagnostics-color=always -g3 -Wall -std=c++17 galaxy.cpp -o day11

run: day11
	./day11 $(ARGS)

clean:
	rm -f ./galaxy
	rm -f ./day11
	
