# Doc referece https://makefiletutorial.com/#why-do-makefiles-exist

day10: pipes.cpp
	g++ -fdiagnostics-color=always -g3 -Wall -std=c++17 pipes.cpp -o day10

run: day10
	./day10 $(ARGS)

clean:
	rm -f ./pipes
	rm -f ./day10
