# Doc referece https://makefiletutorial.com/#why-do-makefiles-exist

day8: HauntedWasteland.cpp
	g++ -fdiagnostics-color=always -g3 -Wall -std=c++0x HauntedWasteland.cpp -o day8

run: day8
	./day8 $(ARGS)

clean:
	rm -f ./day8
